apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: default
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{Your Project_ID}}/secrets/EJABBERD_PASSWORD/versions/1" 
        fileName: "secret.data"
      - resourceName: "projects/{{Your Project_ID}}/secrets/JWT_SECRET/versions/1"
        fileName: "jwt.secret"
      - resourceName: "projects/{{Your Project_ID}}/secrets/AUTHENTICATION_PASSWORD/versions/1"
        fileName: "mapstorage.secret"
      - resourceName: "projects/{{Your Project_ID}}/secrets/EJABBERD_JWT_SECRET/versions/1"
        fileName: "ejabberd-jwt-secret"
      - resourceName: "projects/{{Your Project_ID}}/secrets/SECRET_KEY/versions/1"
        fileName: "secret-key.secret"
      - resourceName: "projects/{{Your Project_ID}}/secrets/slack-bot-token/versions/1"
        fileName: "slack-token.secret"
  secretObjects:
    - secretName: slack-bot-token
      type: Opaque
      data:
        - objectName: slack-token.secret
          key: token
    - secretName: secret-key
      type: Opaque
      data:
        - objectName: secret-key.secret
          key: secret
    - secretName: ejabberd-password
      type: Opaque
      data:
        - objectName: secret.data
          key: name
    - secretName: jwt-secret
      type: Opaque
      data:
        - objectName: jwt.secret
          key: jwt
    - secretName: auth-password
      type: Opaque
      data:
        - objectName: mapstorage.secret
          key: mapstorage-pass
    - secretName: ejabberd-jwt
      type: Opaque
      data:
        - objectName: ejabberd-jwt-secret
          key: eja-jwt-sec

